version: "3"
services:
  hub:
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile.hub
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/srv/jupyterhub
